[package]
name = "ps1-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
time = { version = "0.3.36", features = [
  "formatting",
  "local-offset",
  "macros",
] }
home = "0.5.9"
